version: '3.8'
services:
  app:
    build: .
    container_name: elderly_care_app
    volumes:
      - .:/app  # Mount the local directory for development
    environment:
      - API_KEY="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"  # Pass API key as env var
      - API_BASE="https://openrouter.ai/api/v1"  # Pass API base as env var
    tty: true  # Keep the container running for CLI input
    stdin_open: true  # Enable interactive input