version: '3.8'

services:
  backend:
    build: ./Backend  # ใช้ Dockerfile ในโฟลเดอร์ backend
    container_name: backend_app
    ports:
      - "8091:8091"
    environment:
      - API_KEY="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"  # Pass API key as env var
      - API_BASE="https://openrouter.ai/api/v1"
      - MONGO_URI=mongodb://mongodb:27017/MLOPs
    depends_on:
      - mongodb
    tty: true
    stdin_open: true

  frontend:
    build: ./Frontend  # ใช้ Dockerfile ในโฟลเดอร์ frontend
    container_name: frontend_app
    ports:
      - "8090:8090"
    environment:
      - BACKEND_URL=http://backend:8091  # เชื่อมต่อกับ backend
    depends_on:
      - backend
    
    mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./Database/mongo-data:/data/db  # เก็บข้อมูลให้ถาวร
      - ./Database/init-scripts:/docker-entrypoint-initdb.d  # เพิ่มโฟลเดอร์สำหรับ script
    command: >
      bash -c "
      mongod --fork --logpath /var/log/mongodb.log --bind_ip_all &&
      sleep 5 &&
      mongoimport --db MLOPs --collection knowledge_base --file /docker-entrypoint-initdb.d/elderly_care_knowledge_base.json --jsonArray &&
      tail -f /dev/null"

