version: '3.8'

services:
  backend:
    build: ./Backend
    container_name: backend_app
    ports:
      - "8091:8091"
    env_file:
      - .env
    depends_on:
      - mongodb
    tty: true
    stdin_open: true

  frontend:
    build: ./Frontend 
    container_name: frontend_app
    ports:
      - "8090:8090"
    environment:
      - BACKEND_URL=http://backend:8091
    depends_on:
      - backend
    
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./Database/mongo-data:/data/db

  translator:
    build: ./Translator
    container_name: translator_app
    ports:
      - "8092:8092"
    env_file:
      - .env


